# Generated by Django 4.1.7 on 2023-05-08 18:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=80)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('gender', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('usern', models.OneToOneField(blank=True, max_length=80, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mycar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_num', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=30)),
                ('car_name', models.CharField(max_length=30)),
                ('car_type', models.CharField(max_length=30)),
                ('from_place', models.CharField(max_length=30)),
                ('to_place', models.CharField(max_length=30)),
                ('from_date', models.DateField(null=True)),
                ('to_date', models.DateField(null=True)),
                ('price', models.FloatField()),
                ('car_img', models.ImageField(blank=True, default='', null=True, upload_to='cars')),
                ('cust', models.ForeignKey(blank=True, max_length=100, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80, unique=True)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('msg', models.CharField(max_length=200)),
                ('cust', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=80, unique=True, verbose_name=website.models.Customer)),
                ('pickup', models.DateField()),
                ('dropoff', models.DateField()),
                ('pick_add', models.CharField(max_length=100)),
                ('drop_add', models.CharField(max_length=100)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.customer')),
            ],
        ),
    ]
