# Generated by Django 5.2.3 on 2025-07-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_mycar_car_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.AlterField(
            model_name='booking',
            name='dropoff',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mycar',
            name='from_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mycar',
            name='to_date',
            field=models.DateTimeField(null=True),
        ),
    ]
