# Generated by Django 5.2.3 on 2025-07-28 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_customer_address_remove_customer_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycar',
            name='car_img',
        ),
        migrations.RemoveField(
            model_name='mycar',
            name='car_name',
        ),
        migrations.RemoveField(
            model_name='mycar',
            name='company',
        ),
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='driving_license_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mycar',
            name='seat_count',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date_added',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='dropoff',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup',
            field=models.DateField(null=True),
        ),
    ]
